const express = require('express');
const router = express.Router();

// JSON data
const jobsData = 
[
 "Accountant",
 "Actor/Actress",
 "Administrative Assistant",
 "Aerospace Engineer",
 "Agricultural Engineer",
 "Air Traffic Controller",
 "Aircraft Mechanic",
 "Ambulance Driver",
 "Analyst",
 "Animator",
 "App Developer",
 "Architect",
 "Art Director",
 "Auditor",
 "Author",
 "Baker",
 "Bank Teller",
 "Barista",
 "Bartender",
 "Biomedical Engineer",
 "Brand Manager",
 "Budget Analyst",
 "Building Inspector",
 "Carpenter",
 "Chef",
 "Chemical Engineer",
 "Chief Executive Officer (CEO)",
 "Chief Financial Officer (CFO)",
 "Chief Operating Officer (COO)",
 "Civil Engineer",
 "Claims Adjuster",
 "Clinical Psychologist",
 "Coach",
 "Computer Programmer",
 "Consultant",
 "Copywriter",
 "Counselor",
 "Customer Service Representative",
 "Data Analyst",
 "Database Administrator",
 "Dental Hygienist",
 "Dentist",
 "Detective",
 "Dietitian",
 "Director",
 "Dispatcher",
 "Drafter",
 "Economist",
 "Editor",
 "Electrician",
 "Engineer",
 "Environmental Scientist",
 "Event Coordinator",
 "Fashion Designer",
 "Financial Analyst",
 "Firefighter",
 "Flight Attendant",
 "Florist",
 "Forensic Scientist",
 "Fundraiser",
 "Game Designer",
 "Geneticist",
 "Geologist",
 "Graphic Designer",
 "Guidance Counselor",
 "Hair Stylist",
 "Health Educator",
 "Human Resources Manager",
 "Illustrator",
 "Information Security Analyst",
 "Insurance Agent",
 "Interior Designer",
 "Interpreter",
 "Janitor",
 "Jeweler",
 "Journalist",
 "Judge",
 "Kindergarten Teacher",
 "Laboratory Technician",
 "Landscaper",
 "Lawyer",
 "Librarian",
 "Loan Officer",
 "Logistics Coordinator",
 "Machinist",
 "Manager",
 "Marketing Coordinator",
 "Massage Therapist",
 "Mechanic",
 "Medical Assistant",
 "Meteorologist",
 "Microbiologist",
 "Military Officer",
 "Model",
 "Mortgage Broker",
 "Nurse",
 "Nutritionist",
 "Occupational Therapist",
 "Office Manager",
 "Optometrist",
 "Paralegal",
 "Paramedic",
 "Pharmacist",
 "Photographer",
 "Physical Therapist",
 "Physician",
 "Pilot",
 "Plumber",
 "Police Officer",
 "Politician",
 "Preschool Teacher",
 "Producer",
 "Professor",
 "Project Manager",
 "Psychiatrist",
 "Public Relations Specialist",
 "Purchasing Manager",
 "Quality Control Inspector",
 "Radiologist",
 "Real Estate Agent",
 "Receptionist",
 "Recruiter",
 "Registered Nurse",
 "Research Scientist",
 "Respiratory Therapist",
 "Restaurant Manager",
 "Retail Sales Associate",
 "Sales Representative",
 "School Counselor",
 "Scientist",
 "Secretary",
 "Security Guard",
 "Social Worker",
 "Software Developer",
 "Speech-Language Pathologist",
 "Stockbroker",
 "Surgeon",
 "Surveyor",
 "Teacher",
 "Technical Writer",
 "Technician",
 "Therapist",
 "Tour Guide",
 "Translator",
 "Travel Agent",
 "Urban Planner",
 "Veterinarian",
 "Video Editor",
 "Volunteer Coordinator",
 "Waiter/Waitress",
 "Web Developer",
 "Welder",
 "Writer"

]



// GET route to retrieve all job titles
router.get('/jobs', (req, res) => {
    res.json(jobsData);
});

module.exports = router;